### ISSUE TITLE
[Bug]: not working in mobile phone

### ISSUE THREAD

**Issue by zen010101** [remotely-save/remotely-save#104]
### What happened?

```
2022-05-02T21:19:35+08:00] remotely-save-1651497575511: abort sync, triggerSource=manual, error while getting_remote_extra_meta
[2022-05-02T21:19:35+08:00] ERROR! MESSAGE: Failed to fetch, STACK: TypeError: Failed to fetch
    at eval (eval at <anonymous> (http://localhost/app.js:1:1), <anonymous>:211:37581)
    at Generator.next (<anonymous>)
    at a (eval at <anonymous> (http://localhost/app.js:1:1), <anonymous>:177:280327)
[2022-05-02T21:20:21+08:00] unloading plugin remotely-save
```

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.22

### Version of Obsidian

0.14.2

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by zen010101** [comment]
我尝试在 PC 端重新建立一个新库，然后重新安装 Remotely Save 并设置好后进行一次同步，把文件上传到 OneDrive ；然后安卓端也重新建立一个库，并安装好 Remotely Save 并设置好，两者使用相同的库名，然后进行同步，遇到的错误跟之前发的一样。怀疑跟 _remotely-save-metadata-on-remote.json 有关。

**Comment by fyears** [comment]
hi， bug 已经找到和修复，请更新到 https://github.com/remotely-save/remotely-save/releases/tag/0.3.23 试一下
