### ISSUE TITLE
OneDrive for Business auth error

### ISSUE THREAD

**Issue by JerryFake** [remotely-save/remotely-save#11]
It seem that there is an error about Onedrive for business authorization.
```
GET https://graph.microsoft.com/v1.0/drive/special/approot/children 403 (Forbidden)
Uncaught (in promise) Error: Access denied
    at Function.constructErrorFromResponse (eval at <anonymous> (app.js:1), <anonymous>:164:52791)
    at Function.eval (eval at <anonymous> (app.js:1), <anonymous>:164:53055)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:130:1278)
    at new Promise (<anonymous>)
    at s (eval at <anonymous> (app.js:1), <anonymous>:130:1023)
    at Function.getError (eval at <anonymous> (app.js:1), <anonymous>:164:52996)
    at Ni.eval (eval at <anonymous> (app.js:1), <anonymous>:164:56990)
    at Generator.throw (<anonymous>)
    at s (eval at <anonymous> (app.js:1), <anonymous>:130:1131)
```
And sorry I type the wrong word "Onedive"

**Comment by chen860456552** [comment]
I also use onedrive to sync. There is no error.

**Comment by JerryFake** [comment]
> I also use onedrive to sync. There is no error.

I know. But I have an E5 Microsoft Developer account and what I use is Onedrive for Business not the Onedrive for Personal.

**Comment by chen860456552** [comment]
E5 maybe not useful.I used joplin before,it support many drive to sync but e5 is not useful.If you are admin ,it maybe work,but i dont test it

**Comment by fyears** [comment]
Thank you for your report.

One possibility is that your business account doesn’t allow this plugin’s oauth2 sign in (A consent from admin needed). Another possibility is that the plugin uses more secure [App Folder](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online) feature which is a *beta* api by MSFT and not implemented on for Business account. Of course there are other possibilities that I am not aware of.

However, I don’t have any OneDrive for Business account, so I cannot do any further investigation. I will add a comment that the function is only tested working on personal accounts (something like *@outlook.com or *@live.com).

**Comment by JerryFake** [comment]
> Thank you for your report.
> 
> One possibility is that your business account doesn’t allow this plugin’s oauth2 sign in (A consent from admin needed). Another possibility is that the plugin uses more secure [App Folder](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online) feature which is a _beta_ api by MSFT and not implemented on for Business account. Of course there are other possibilities that I am not aware of.
> 
> However, I don’t have any OneDrive for Business account, so I cannot do any further investigation. I will add a comment that the function is only tested working on personal accounts (something like *@outlook.com or *@live.com).

I can offer my E5 account and I am the admin. Do you have a try to solve it?

**Comment by fyears** [comment]
Firstly, thank you, but I do NOT need your account.

I have checked out the docs of OneDrive for business, and **maybe** it's possible to add some supports. So I reopen the issue to remind me of the optimizations in the future (when I have more free time...). But it's not implemented in these days, sorry.

**Comment by JerryFake** [comment]
> Firstly, thank you, but I do NOT need your account.
> 
> I have checked out the docs of OneDrive for business, and **maybe** it's possible to add some supports. So I reopen the issue to remind me of the optimizations in the future (when I have more free time...). But it will not be implemented in these days, sorry.

**Comment by JerryFake** [comment]
> > Firstly, thank you, but I do NOT need your account.
> > I have checked out the docs of OneDrive for business, and **maybe** it's possible to add some supports. So I reopen the issue to remind me of the optimizations in the future (when I have more free time...). But it will not be implemented in these days, sorry.

I get it.

**Comment by PassionPenguin** [comment]
@fyears thx for your development after all, what i found this time is that after granting admin consent for the account added the remotely-save application, it's running without any exception

首先非常感谢你对这个插件的开发。

我尝试了一下，在 grant consent to 登录并添加插件的那个账号之后，一切都可以正常运作。

（可能需要管理员权限，没有添加任何额外权限。也就是说，如果要使用这个插件，可能需要管理员授权）

![图一：Application Overview](https://user-images.githubusercontent.com/41184947/200585935-11271f84-1291-44e6-b2e5-43cc2eb7dfe5.png)

![图二：Application Consent & Permissions](https://user-images.githubusercontent.com/41184947/200586006-2d98b2d9-c9c4-4307-b5e8-24a78c58723f.png)

**Comment by PassionPenguin** [comment]
Currently it works well under the admin consent.

![image](https://user-images.githubusercontent.com/41184947/200588927-4bc60067-a0a1-4eb3-96d1-1d64609f5836.png)

**Comment by CXido** [comment]
![msedge_MJ1sMRZtmS](https://user-images.githubusercontent.com/55381745/200735364-199d2036-3b0f-4e9b-aa45-1abe15e7e803.png)
![image](https://user-images.githubusercontent.com/55381745/200735395-79d5e32d-edad-4195-b8d9-b7ecc3d1b859.png)

感谢，已经连接上去了

**Comment by PassionPenguin** [comment]
> ![msedge_MJ1sMRZtmS](https://user-images.githubusercontent.com/55381745/200735364-199d2036-3b0f-4e9b-aa45-1abe15e7e803.png) ![image](https://user-images.githubusercontent.com/55381745/200735395-79d5e32d-edad-4195-b8d9-b7ecc3d1b859.png)
> 
> 感谢，已经连接上去了

Noted that if you are an E5 developer account user, it's highly recommended to cover your admin name or account name in case any malicious email attack takes place.

**Comment by CXido** [comment]
> > ![msedge_MJ1sMRZtmS](https://user-images.githubusercontent.com/55381745/200735364-199d2036-3b0f-4e9b-aa45-1abe15e7e803.png) ![image](https://user-images.githubusercontent.com/55381745/200735395-79d5e32d-edad-4195-b8d9-b7ecc3d1b859.png)
> > 感谢，已经连接上去了
> 
> Noted that if you are an E5 developer account user, it's highly recommended to cover your admin name or account name in case any malicious email attack takes place.

感谢提醒，已经打码了，不过你引用的回复好像不会更新图片

**Comment by SkysCrystal** [comment]
> @fyears thx for your development after all, what i found this time is that after granting admin consent for the account added the remotely-save application, it's running without any exception.
> 
> that's is, you may need admin consent before authenticating by an admin user via azure active directory.
> 
> 首先非常感谢你对这个插件的开发。
> 
> 我尝试了一下，在 grant consent to 登录并添加插件的那个账号之后，一切都可以正常运作。
> 
> （可能需要管理员权限，没有添加任何额外权限。也就是说，如果要使用这个插件，可能需要管理员在 AAD 上面授权）
> 
> ![图一：Application Overview](https://user-images.githubusercontent.com/41184947/200585935-11271f84-1291-44e6-b2e5-43cc2eb7dfe5.png)
> 
> ![图二：Application Consent & Permissions](https://user-images.githubusercontent.com/41184947/200586006-2d98b2d9-c9c4-4307-b5e8-24a78c58723f.png)
> 
> @sometimes-naaive @hi-yiyang @JerryFake

感谢讨论、分享，我也成功连接 E5 onedrive 了。
但我有个问题，同步文件存储在 onedrive 的哪里？在个人 Onedrive 连接 remotely-save 后会在根目录下创建 `应用/remotely-save` 文件夹。我找了 E5账号 onedrive 空间里都没有新建的文件夹。
![](https://pan.swin.ltd/d/share/Figurebed/202302071233228.png)

我想找到 E5 里头的这个文件夹方便之后备份。

**Comment by PassionPenguin** [comment]
> > @fyears thx for your development after all, what i found this time is that after granting admin consent for the account added the remotely-save application, it's running without any exception.
> > that's is, you may need admin consent before authenticating by an admin user via azure active directory.
> > 首先非常感谢你对这个插件的开发。
> > 我尝试了一下，在 grant consent to 登录并添加插件的那个账号之后，一切都可以正常运作。
> > （可能需要管理员权限，没有添加任何额外权限。也就是说，如果要使用这个插件，可能需要管理员在 AAD 上面授权）
> > ![图一：Application Overview](https://user-images.githubusercontent.com/41184947/200585935-11271f84-1291-44e6-b2e5-43cc2eb7dfe5.png)
> > ![图二：Application Consent & Permissions](https://user-images.githubusercontent.com/41184947/200586006-2d98b2d9-c9c4-4307-b5e8-24a78c58723f.png)
> > @sometimes-naaive @hi-yiyang @JerryFake
> 
> 感谢讨论、分享，我也成功连接 E5 onedrive 了。 但我有个问题，同步文件存储在 onedrive 的哪里？在个人 Onedrive 连接 remotely-save 后会在根目录下创建 `应用/remotely-save` 文件夹。我找了 E5账号 onedrive 空间里都没有新建的文件夹。 ![](https://camo.githubusercontent.com/52e8ef90501c13cd558526f1e7c6482f35276c81fe268b633c34eeb366ce148b/68747470733a2f2f70616e2e7377696e2e6c74642f642f73686172652f4669677572656265642f3230323330323037313233333232382e706e67)
> 
> 我想找到 E5 里头的这个文件夹方便之后备份。

TBH, I just put the vault inside the drive, thus after syncing it's still there

**Comment by PassionPenguin** [comment]
> > > @fyears thx for your development after all, what i found this time is that after granting admin consent for the account added the remotely-save application, it's running without any exception.
> > > that's is, you may need admin consent before authenticating by an admin user via azure active directory.
> > > 首先非常感谢你对这个插件的开发。
> > > 我尝试了一下，在 grant consent to 登录并添加插件的那个账号之后，一切都可以正常运作。
> > > （可能需要管理员权限，没有添加任何额外权限。也就是说，如果要使用这个插件，可能需要管理员在 AAD 上面授权）
> > > ![图一：Application Overview](https://user-images.githubusercontent.com/41184947/200585935-11271f84-1291-44e6-b2e5-43cc2eb7dfe5.png)
> > > ![图二：Application Consent & Permissions](https://user-images.githubusercontent.com/41184947/200586006-2d98b2d9-c9c4-4307-b5e8-24a78c58723f.png)
> > > @sometimes-naaive @hi-yiyang @JerryFake
> > 
> > 
> > 感谢讨论、分享，我也成功连接 E5 onedrive 了。 但我有个问题，同步文件存储在 onedrive 的哪里？在个人 Onedrive 连接 remotely-save 后会在根目录下创建 `应用/remotely-save` 文件夹。我找了 E5账号 onedrive 空间里都没有新建的文件夹。 ![](https://camo.githubusercontent.com/52e8ef90501c13cd558526f1e7c6482f35276c81fe268b633c34eeb366ce148b/68747470733a2f2f70616e2e7377696e2e6c74642f642f73686172652f4669677572656265642f3230323330323037313233333232382e706e67)
> > 我想找到 E5 里头的这个文件夹方便之后备份。
> 
> TBH, I just put the vault inside the drive, thus after syncing it's still there

The reason I use the plugin is just to open files in mobile Obsidian without syncing the whole folder into my phone.

**Comment by SkysCrystal** [comment]
> The reason I use the plugin is just to open files in mobile Obsidian without syncing the whole folder into my phone.
I got it! Thanks for your reply. I will use it more flexible~

**Comment by EpicPilgrim** [comment]
I have granted admin consent to "remotely-save" in my own M365 tenant so I can use OneDrive for Business but the "Remotely Save" modal window in Obsidian is just stuck on "Connecting to OneDrive... Please DO NOT close this modal." Where would I look to see why this didn't work for me?

**Comment by PassionPenguin** [comment]
> I have granted admin consent to "remotely-save" in my own M365 tenant so I can use OneDrive for Business but the "Remotely Save" modal window in Obsidian is just stuck on "Connecting to OneDrive... Please DO NOT close this modal." Console shows this:
> 
> ```
> start updating local info of OneDrive token
> plugin:remotely-save:216 finish updating local info of Onedrive token
> plugin:remotely-save:211 Onedrive accessToken updated
> app.js:1 Uncaught (in promise) Error: Request failed, status 403
>     at new t (app.js:1:1668026)
>     at tU (app.js:1:1668218)
>     at app.js:1:1668895
>     at app.js:1:235927
>     at Object.next (app.js:1:236032)
>     at a (app.js:1:234750)
> ```
> 
> Any thoughts on what may be different between the people with working Onedrive for Business connections, and myself?

it's 403, possibly because it's not set up well...
however, i have no od-e5 account at the moment, i may not be able to check it for you.
you may try check all the priviledges that are required, regenerate an access token for the app, regrant the app. after all, onedrive business-onedrive personal are designed to have the same apis, meaning that they should work well if you follow the onedrive personal docs.

**Comment by rowansmithau** [comment]
Confirmed today that as an E3 customer I tried to get remotely-save to work with onedrive, went through the auth process and obsidian sat there trying to process it. At that point I killed it, went into Azure AD > Applications > Enterprise Applications > remotely-save > Permissions and used the Grant Admin Consent button, then opened Obsidian again and ran through the remotely-save onedrive auth process and it now works.

**Comment by PassionPenguin** [comment]
> Confirmed today that as an E3 customer I tried to get remotely-save to work with onedrive, went through the auth process and obsidian sat there trying to process it. At that point I killed it, went into Azure AD > Applications > Enterprise Applications > remotely-save > Permissions and used the Grant Admin Consent button, then opened Obsidian again and ran through the remotely-save onedrive auth process and it now works.

that's it. the apis are the same and the logics should work between different kinds of onedrive users with Graph api enabled.

**Comment by sailcom** [comment]
**Note to users who use the E5 developer account:** 
If you are using a onedrive (for business) account for synchronization, your files will be uploaded to the shared library of the enterprise after synchronization, and other personnel in the enterprise (group) have permission to see these files.
**The solution is:** 
log in with an administrator account, adjust the administrative access rights of the remotely-save folder, and delete the access rights of other people. This prevents your private files from being accessed by others.

**请使用E5开发者账号的用户们注意：**
如果您使用的是onedrive(for business)的账号进行同步，同步后您的文件会被上传至企业的共享库中，企业(群组)内的其他人员都有权限看到这些文件。
**解决方案是：**
使用管理员账户登入，调整remotely-save文件夹的管理访问权限，将其他人员的访问权限删除。这样就可以避免您的私密文件被其他人员访问。

**Comment by dengyakui** [comment]
My E5 OneDrive Successfuly linked , bebow is the step:
1.  Open Obsidian app's plugin option page,  just select OneDrivePersonal, it will works for E5 office subscription
    
![image](https://github.com/remotely-save/remotely-save/assets/3945919/af4d6289-dbb3-4ff4-98a3-6a9a51e53595)

2.  Click the auth url,  and login your E5 admin account in your browser
    
![image](https://github.com/remotely-save/remotely-save/assets/3945919/fab8b9d5-c55f-4f2b-8545-097e2845fc4d)
![image](https://github.com/remotely-save/remotely-save/assets/3945919/01a54a19-4e54-4021-8862-00fb681133f3)

4.  After login success first time,  will prompt you to Grant Some Permissions, But may failed for your login account was not admin, you should use admin account login info  Azure portal to grant  some permission.
![image](https://github.com/remotely-save/remotely-save/assets/3945919/68861244-f928-48d6-aaba-5d4a8846b270)

5. Find the **remotely-save** application from EnterpriseApplications menu 
6. Enter the app settings page, find the permission section, make sure these requesed permissions was granted 
![image](https://github.com/remotely-save/remotely-save/assets/3945919/aed3f2ca-02fb-458a-abf4-ff1b5a6763d4)

8. Back to Obsidian plugin option page, re-click the auth button, and do login, if there is continue button, you are success.
![image](https://github.com/remotely-save/remotely-save/assets/3945919/cb598888-d6aa-46f9-a409-cedd0dbf403a)
![image](https://github.com/remotely-save/remotely-save/assets/3945919/166a90f2-328a-41f5-95fa-0f7577d7593f)

9.  Click the check button to verify OneDrive connection is Ok
![image](https://github.com/remotely-save/remotely-save/assets/3945919/db2157b9-ac49-47c0-845a-d1a4282a8031)
10. Click the sync  button to sync local vault's files to OneDrive
![image](https://github.com/remotely-save/remotely-save/assets/3945919/3f7dd46f-2038-417b-bfe5-a0b6ccc9532e)

12. Check the remote vault folder path.  By default,  the remote vault folder was created on SharePoint, Not One drive !!!
      You can add short link to OneDrive for easy access.
![image](https://github.com/remotely-save/remotely-save/assets/3945919/a4d14a77-5fbb-4fa4-a466-2f01ea21dccf)


14. After add short link, you can visit your Vault from OneDrive, Congratulations!
![image](https://github.com/remotely-save/remotely-save/assets/3945919/9e43b311-6be9-4fd3-9ddd-d6563f9acab8)

**Comment by fyears** [comment]
Thank you for everyone for the detailed screenshots and steps!!! I would like to add some ref in readme to this issue!!! It seems the key point is granting the permission from admin, and going to sharepoint not onedrive, and paying attention to the permissions visible for others.

谢谢各位的截图和步骤！我在文档更新一下链接！看上去这里有几个注意点：管理员授权、sharepoint vs onedrive、文档可能对其他人可视需要设置。

**Comment by DeltaScratchpad** [comment]
Is there any update on supporting this properly? given its been 3 years without official movement.

**Comment by fuzzy76** [comment]
Yes, I would assume most users do *not* have admin rights for their M365 tenant.
