### ISSUE TITLE
[Bug]:  Webdav 502 error, only folders synced but not files [logs & screenshot]

### ISSUE THREAD

**Issue by lovitus** [remotely-save/remotely-save#190]
### What happened?

picture 1:  connection is stable,
p2: always return 502 when try to sync
p3: folders created successfully on webdav server, but no any files.

![image](https://user-images.githubusercontent.com/14361541/189645872-69f6e6be-cab7-4db6-ac4c-e50f3b13e787.png)
![image](https://user-images.githubusercontent.com/14361541/189646068-ed22450e-c481-4ea0-afc7-5960595e96ea.png)
![image](https://user-images.githubusercontent.com/14361541/189646180-a2ce7e20-6265-4369-8965-e5b08bc97e54.png)

Logger history found:

```text
[2022-09-12T19:44:44+08:00] db deleted
[2022-09-12T19:44:50+08:00] remotely-save-1662983090904: start sync, triggerSource=manual
[2022-09-12T19:44:52+08:00] ERROR! MESSAGE: Request failed, status 502, STACK: Error: Request failed, status 502
    at new t (app://obsidian.md/app.js:1:1454507)
    at VN (app://obsidian.md/app.js:1:1454662)
    at app://obsidian.md/app.js:1:1455339
    at app://obsidian.md/app.js:1:235078
    at Object.next (app://obsidian.md/app.js:1:235183)
    at s (app://obsidian.md/app.js:1:233922)
[2022-09-12T19:44:57+08:00] remotely-save-1662983097667: start sync, triggerSource=manual
[2022-09-12T19:45:00+08:00] ERROR! MESSAGE: Request failed, status 502, STACK: Error: Request failed, status 502
    at new t (app://obsidian.md/app.js:1:1454507)
    at VN (app://obsidian.md/app.js:1:1454662)
    at app://obsidian.md/app.js:1:1455339
    at app://obsidian.md/app.js:1:235078
    at Object.next (app://obsidian.md/app.js:1:235183)
    at s (app://obsidian.md/app.js:1:233922)
[2022-09-12T19:45:05+08:00] remotely-save-1662983105870: start sync, triggerSource=manual
[2022-09-12T19:45:07+08:00] remotely-save-1662983107237: abort sync, triggerSource=manual, error while getting_remote_files_list
[2022-09-12T19:45:07+08:00] ERROR! MESSAGE: Request failed, status 502, STACK: Error: Request failed, status 502
    at new t (app://obsidian.md/app.js:1:1454507)
    at VN (app://obsidian.md/app.js:1:1454662)
    at app://obsidian.md/app.js:1:1455339
    at app://obsidian.md/app.js:1:235078
    at Object.next (app://obsidian.md/app.js:1:235183)
    at s (app://obsidian.md/app.js:1:233922)
```

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by keeyangyy** [comment]
坚果云有个单页限制，一个文件夹里好像最多900个文件，多了就会分页，插件这边没有分页续读，认为是同步完成了。

**Comment by fyears** [comment]
坚果云有如上问题，不是标准的webdav 格式。比较难解决。
