### ISSUE TITLE
[Bug]: onedrive remotely save failed!

### ISSUE THREAD

**Issue by ayuayue** [remotely-save/remotely-save#197]
### What happened?

[2022-09-25T00:24:35+08:00] getJson, theUrl=https://graph.microsoft.com/v1.0/drive/special/approot/children
[2022-09-25T00:24:35+08:00] postJson, theUrl=https://graph.microsoft.com/v1.0/drive/special/approot/children
[2022-09-25T00:24:35+08:00] ERROR! MESSAGE: Request failed, status 400, STACK: Error: Request failed, status 400
    at new t (app://obsidian.md/app.js:1:1454507)
    at VN (app://obsidian.md/app.js:1:1454662)
    at app://obsidian.md/app.js:1:1455339
    at app://obsidian.md/app.js:1:235078
    at Object.next (app://obsidian.md/app.js:1:235183)
    at s (app://obsidian.md/app.js:1:233922)

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by ayuayue** [comment]
Uninstalling and reinstallation seems to be better again
