### ISSUE TITLE
[Bug]: sync mp4 may cause Android Obsidian crash?

### ISSUE THREAD

**Issue by sun2ot** [remotely-save/remotely-save#265]
### What happened?

I embeded a `mp4` file about 37 MB in my document. And when I use `S3` by remotely save to sync data, the Android Obsidian APP will crash. It means not to reamin black screen, but quit quickly. Here is the bug report from my Xiaomi Phone. Hope it will help you.

```
java.lang.OutOfMemoryError: Failed to allocate a 52309608 byte allocation with 7226096 free bytes and 7056KB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:97)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
	at android.util.Base64.encodeToString(Base64.java:458)
	at com.capacitorjs.plugins.app.AppPlugin.requestUrlAndroid(AppPlugin.java:249)
	at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$2$com-capacitorjs-plugins-app-AppPlugin(AppPlugin.java:157)
	at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

I do not know what cause this problem. So I tried to set the `Parts Concurrency` and `Concurrency` in Advanced Settings to just `1`. Obviously it didn't work......

Hope to your reply. Thank you!

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by zhihang-yi** [comment]
Now I move the `mp4` file to the local directory in my phone manually. It can be played normally.

**Comment by Kelatte** [comment]
I found this bug too. Stepping big file works on me

**Comment by fyears** [comment]
Yes Skip Large Files should help. The error shows "OOM" (out of memory) because the file is too large.
