### ISSUE TITLE
[Bug]: 403 on third s3 bucket connection

### ISSUE THREAD

**Issue by jchud13** [remotely-save/remotely-save#365]
### What happened?

Setting up the plugin, everything is working fine on linux installation and mobile installation.  

On third installation on windows, with verified all the same credentials I get a 403 error. Sync plans say "No sync plans found" and db console just shows the 403.

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

Current

### Version of Obsidian

Current

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by jchud13** [comment]
It solved itself XD

**Comment by jchud13** [comment]
Came back. No changes would cause this not to connect. Other instances still work fine. 

Only relevant output. 

Logger history found:

```text
[2023-09-26T23:50:32-04:00] remotely-save-1695786632553: start sync, triggerSource=manual
[2023-09-26T23:50:32-04:00] remotely-save-1695786632661: abort sync, triggerSource=manual, error while getting_remote_files_list
[2023-09-26T23:50:32-04:00] ERROR! MESSAGE: Request failed, status 403, STACK: Error: Request failed, status 403
    at new t (app://obsidian.md/app.js:1:265647)
    at cn (app://obsidian.md/app.js:1:265839)
    at app://obsidian.md/app.js:1:266515
    at app://obsidian.md/app.js:1:237030
    at Object.next (app://obsidian.md/app.js:1:237135)
    at a (app://obsidian.md/app.js:1:235853)
```


Cannot connect to s3 bucket. Triple checked all values align. 

Just unsure how to diagnose, and why it randomly started working before with no changes.

**Comment by chrvip** [comment]
> It solved itself XD

Why and How? Works on PC and same issue on Android.

**Comment by fyears** [comment]
Would you like to directly copy the file `data.json` from linux to windows and try again?

**Comment by fyears** [comment]
cannot reproduce. feel free to create a new issue if more hints are found
