### ISSUE TITLE
[Bug]: 运行插件进行同步导致ob自动退出

### ISSUE THREAD

**Issue by pisice** [remotely-save/remotely-save#443]
### What happened?

MIUI使用这个插件同步的时候obsidian程序会自动退出，分别试了miui 12/13/14系统，现象一样。如果插件设置为开始自动运行，打开OB后很快程序自动退出。同样插件和版本windows版无此问题。OB卸载remotely save后无自动退出现象。

服务器：webdav
win 7运行IIS7自建webdav服务器，公网IP+端口映射

系统：MIUI -V14.0.2.0.TJJCNXM
安卓版本：13
内核：4.19.157-perf-g35fcd5da188a

- 系统报错：       
        应用名称：Obsidian
        应用版本：1.4.16
        问题发生时间：2024-01-14 18:36:57
        问题Trace：
        java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 100663296 free bytes and 142MB until 
          OOM, target footprint 219538496, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3766)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:650)
	at java.lang.StringBuilder.append_(StringBuilder.java:203)
	at org.json.JSONStringer.string(JSONStringer.java:354)
	at org.json.JSONStringer.value(JSONStringer.java:261)
	at org.json.JSONObject.writeTo(JSONObject.java:734)
	at org.json.JSONStringer.value(JSONStringer.java:246)
	at org.json.JSONObject.writeTo(JSONObject.java:734)
	at org.json.JSONObject.toString(JSONObject.java:702)
	at com.getcapacitor.PluginResult.toString(PluginResult.java:67)
	at com.getcapacitor.MessageHandler.sendResponseMessage(MessageHandler.java:103)
	at com.getcapacitor.PluginCall.resolve(PluginCall.java:74)
	at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$2$com-capacitorjs-plugins-app- 
            AppPlugin(AppPlugin.java:157)
	at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (ownCloud)

### Version of the plugin

0.3.35

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请进入设置，设定“跳过大文件”。这里是因为手机处理不了太大文件，无法绕过。
