### ISSUE TITLE
[Bug]: android版运行插件Obsidian闪退

### ISSUE THREAD

**Issue by pisice** [remotely-save/remotely-save#446]
### What happened?

现象：安卓版Obsidian运行插件后程序自动退出，不运行remotely save没有闪退现象，系统报错如下。pc端运行插件可正常同步。服务器为自己搭建的webdav。

服务器环境：win7系统，IIS7搭建的webdav，路由器端口映射+公网IP。

系统：MIUI 14.0.2
Android版本：13
内核版本：4.19.157

应用名称：Obsidian
应用版本：1.4.16
问题发生时间：2024-01-14 18:36:57
问题Trace：
java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 100663296 free bytes and 142MB until OOM, target footprint 219538496, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3766)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:650)
	at java.lang.StringBuilder.append(StringBuilder.java:203)
	at org.json.JSONStringer.string(JSONStringer.java:354)
	at org.json.JSONStringer.value(JSONStringer.java:261)
	at org.json.JSONObject.writeTo(JSONObject.java:734)
	at org.json.JSONStringer.value(JSONStringer.java:246)
	at org.json.JSONObject.writeTo(JSONObject.java:734)
	at org.json.JSONObject.toString(JSONObject.java:702)
	at com.getcapacitor.PluginResult.toString(PluginResult.java:67)
	at com.getcapacitor.MessageHandler.sendResponseMessage(MessageHandler.java:103)
	at com.getcapacitor.PluginCall.resolve(PluginCall.java:74)
	at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$2$com-capacitorjs-plugins-app-AppPlugin(AppPlugin.java:157)
	at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

![49ab02b64d13d9c780dcc158cf8d1f5](https://github.com/remotely-save/remotely-save/assets/23545791/1479570c-0820-44fd-a143-65481ab94a2f)
![8c5826e4c20661e41283a42aa62a9c9](https://github.com/remotely-save/remotely-save/assets/23545791/5cbfa0aa-566f-4baf-a89f-aa45d92a272c)
![d15c255feed5f37e22ae2938233183c](https://github.com/remotely-save/remotely-save/assets/23545791/4577b399-0133-47cd-a5f3-6e3b4f3ab094)
![30ebd4bca562a9caf43c8a627d00ac8](https://github.com/remotely-save/remotely-save/assets/23545791/79b936fa-e875-4d75-bc55-becc76fe2a17)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.35

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
和 #443 重复了，同一个问题，处理不了大文件，可以设置跳过大文件
