### ISSUE TITLE
[Bug]: Android手机同步造成obsidian闪退

### ISSUE THREAD

**Issue by flyman1573** [remotely-save/remotely-save#500]
### What happened?

1.mac上已同步完成，在云存储里能看到上传的文件。
2.在小米手机(小米10 MiUI 14.0.4)上同步，obsidian闪退
![image](https://github.com/remotely-save/remotely-save/assets/72484504/e2b48b55-8c89-4b44-89dc-0af72934ad40)
java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 138MB until OOM, target footprint 148177848, growth limit 268435456
 at java.util.Arrays.copyOf(Arrays.java:3766)
 at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
 at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:650)
 at java.lang.StringBuilder.append(StringBuilder.java:203)
 at org.json.JSONStringer.string(JSONStringer.java:354)
 at org.json.JSONStringer.value(JSONStringer.java:261)
 at org.json.JSONObject.writeTo(JSONObject.java:734)
 at org.json.JSONStringer.value(JSONStringer.java:246)
 at org.json.JSONObject.writeTo(JSONObject.java:734)
 at org.json.JSONObject.toString(JSONObject.java:702)
 at com.getcapacitor.PluginResult.toString(PluginResult.java:67)
 at com.getcapacitor.MessageHandler.sendResponseMessage(MessageHandler.java:103)
 at com.getcapacitor.PluginCall.resolve(PluginCall.java:74)
 at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$2$com-capacitorjs-plugins-app-AppPlugin(AppPlugin.java:157)
 at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda2.run(Unknown Source:4)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.3.40

### Version of Obsidian

mac 1.5.3  android 1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
out of memory 

有文件太大了。

建议设置“跳过大文件”
