### ISSUE TITLE
[Bug]: WebDav syncing .obsidian file fails

### ISSUE THREAD

**Issue by tachyonicClock** [remotely-save/remotely-save#81]
### What happened?

Remotely Save Error
```
VM218:231 AggregateError: 
    Error: .obsidian/: Invalid response: 405 Method Not Allowed
        at eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:226:307399)
    at eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:226:307559)
    at Generator.next (<anonymous>)
    at a (eval at <anonymous> (app.js:1:1490278), <anonymous>:192:1080)
```

Nginx Error
```
2022/04/16 14:04:22 [error] 512#512: *4 mkdir() "/data/webdav/obsidian/.obsidian" failed (17: File exists), client: 101.100.131.220, server: webdav.*, request: "MKCOL /obsidian/.obsidian/ HTTP/2.0", host: "example.com"
```

From these logs it appears to be an issue with the sync algorithm that interprets an "Already Exists Error" as a real error. Note that it works fine on the first upload (before .obsidian exists) 

### What OS are you using?

Linux

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.18

### Version of Obsidian

0.14.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Could you please export the corresponding sync plan following the instructions here? 

https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md

**Comment by tachyonicClock** [comment]
Sorry about the slow reply. See attached for a minimal vault. 
Sync plans found:

```json
{
  "ts": 1650840100459,
  "tsFmt": "2022-04-25T10:41:40+12:00",
  "remoteType": "webdav",
  "mixedStates": {
    "test_note.md": {
      "key": "test_note.md",
      "existRemote": true,
      "mtimeRemote": 1650840027704,
      "mtimeRemoteFmt": "2022-04-25T10:40:27+12:00",
      "sizeRemote": 0,
      "remoteEncryptedKey": "test_note.md",
      "changeRemoteMtimeUsingMapping": true,
      "existLocal": true,
      "mtimeLocal": 1650840027704,
      "mtimeLocalFmt": "2022-04-25T10:40:27+12:00",
      "sizeLocal": 0,
      "changeLocalMtimeUsingMapping": true,
      "decision": "skipUploading",
      "decisionBranch": 1
    },
    ".obsidian/": {
      "key": ".obsidian/",
      "existLocal": true,
      "mtimeLocal": 1650839896545,
      "mtimeLocalFmt": "2022-04-25T10:38:16+12:00",
      "sizeLocal": 4096,
      "existRemote": false,
      "decision": "createFolder",
      "decisionBranch": 13
    },
    ".obsidian/plugins/": {
      "key": ".obsidian/plugins/",
      "existLocal": true,
      "mtimeLocal": 1650839884757,
      "mtimeLocalFmt": "2022-04-25T10:38:04+12:00",
      "sizeLocal": 4096,
      "existRemote": false,
      "decision": "createFolder",
      "decisionBranch": 13
    },
    ".obsidian/app.json": {
      "key": ".obsidian/app.json",
      "existLocal": true,
      "mtimeLocal": 1650839865349,
      "mtimeLocalFmt": "2022-04-25T10:37:45+12:00",
      "sizeLocal": 2,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/appearance.json": {
      "key": ".obsidian/appearance.json",
      "existLocal": true,
      "mtimeLocal": 1650839865349,
      "mtimeLocalFmt": "2022-04-25T10:37:45+12:00",
      "sizeLocal": 2,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/community-plugins.json": {
      "key": ".obsidian/community-plugins.json",
      "existLocal": true,
      "mtimeLocal": 1650839896549,
      "mtimeLocalFmt": "2022-04-25T10:38:16+12:00",
      "sizeLocal": 21,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/core-plugins.json": {
      "key": ".obsidian/core-plugins.json",
      "existLocal": true,
      "mtimeLocal": 1650839864973,
      "mtimeLocalFmt": "2022-04-25T10:37:44+12:00",
      "sizeLocal": 241,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/hotkeys.json": {
      "key": ".obsidian/hotkeys.json",
      "existLocal": true,
      "mtimeLocal": 1650839864357,
      "mtimeLocalFmt": "2022-04-25T10:37:44+12:00",
      "sizeLocal": 2,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/workspace": {
      "key": ".obsidian/workspace",
      "existLocal": true,
      "mtimeLocal": 1650840028700,
      "mtimeLocalFmt": "2022-04-25T10:40:28+12:00",
      "sizeLocal": 2093,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/": {
      "key": ".obsidian/plugins/remotely-save/",
      "existLocal": true,
      "mtimeLocal": 1650839896481,
      "mtimeLocalFmt": "2022-04-25T10:38:16+12:00",
      "sizeLocal": 4096,
      "existRemote": false,
      "decision": "createFolder",
      "decisionBranch": 13
    },
    ".obsidian/plugins/remotely-save/.gitignore": {
      "key": ".obsidian/plugins/remotely-save/.gitignore",
      "existLocal": true,
      "mtimeLocal": 1650839895549,
      "mtimeLocalFmt": "2022-04-25T10:38:15+12:00",
      "sizeLocal": 10,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/data.json": {
      "key": ".obsidian/plugins/remotely-save/data.json",
      "existLocal": true,
      "mtimeLocal": 1650840089524,
      "mtimeLocalFmt": "2022-04-25T10:41:29+12:00",
      "sizeLocal": 1703,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/main.js": {
      "key": ".obsidian/plugins/remotely-save/main.js",
      "existLocal": true,
      "mtimeLocal": 1650839885809,
      "mtimeLocalFmt": "2022-04-25T10:38:05+12:00",
      "sizeLocal": 2051374,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/manifest.json": {
      "key": ".obsidian/plugins/remotely-save/manifest.json",
      "existLocal": true,
      "mtimeLocal": 1650839884761,
      "mtimeLocalFmt": "2022-04-25T10:38:04+12:00",
      "sizeLocal": 330,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/styles.css": {
      "key": ".obsidian/plugins/remotely-save/styles.css",
      "existLocal": true,
      "mtimeLocal": 1650839886633,
      "mtimeLocalFmt": "2022-04-25T10:38:06+12:00",
      "sizeLocal": 691,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    "Untitled.md": {
      "key": "Untitled.md",
      "deltimeRemote": 1650840027704,
      "deltimeRemoteFmt": "2022-04-25T10:40:27+12:00",
      "existLocal": false,
      "existRemote": false,
      "decision": "keepRemoteDelHist",
      "decisionBranch": 7
    }
  }
}
```

```json
{
  "ts": 1650840092891,
  "tsFmt": "2022-04-25T10:41:32+12:00",
  "remoteType": "webdav",
  "mixedStates": {
    "test_note.md": {
      "key": "test_note.md",
      "existRemote": true,
      "mtimeRemote": 1650840027704,
      "mtimeRemoteFmt": "2022-04-25T10:40:27+12:00",
      "sizeRemote": 0,
      "remoteEncryptedKey": "test_note.md",
      "changeRemoteMtimeUsingMapping": true,
      "existLocal": true,
      "mtimeLocal": 1650840027704,
      "mtimeLocalFmt": "2022-04-25T10:40:27+12:00",
      "sizeLocal": 0,
      "changeLocalMtimeUsingMapping": true,
      "decision": "skipUploading",
      "decisionBranch": 1
    },
    ".obsidian/": {
      "key": ".obsidian/",
      "existLocal": true,
      "mtimeLocal": 1650839896545,
      "mtimeLocalFmt": "2022-04-25T10:38:16+12:00",
      "sizeLocal": 4096,
      "existRemote": false,
      "decision": "createFolder",
      "decisionBranch": 13
    },
    ".obsidian/plugins/": {
      "key": ".obsidian/plugins/",
      "existLocal": true,
      "mtimeLocal": 1650839884757,
      "mtimeLocalFmt": "2022-04-25T10:38:04+12:00",
      "sizeLocal": 4096,
      "existRemote": false,
      "decision": "createFolder",
      "decisionBranch": 13
    },
    ".obsidian/app.json": {
      "key": ".obsidian/app.json",
      "existLocal": true,
      "mtimeLocal": 1650839865349,
      "mtimeLocalFmt": "2022-04-25T10:37:45+12:00",
      "sizeLocal": 2,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/appearance.json": {
      "key": ".obsidian/appearance.json",
      "existLocal": true,
      "mtimeLocal": 1650839865349,
      "mtimeLocalFmt": "2022-04-25T10:37:45+12:00",
      "sizeLocal": 2,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/community-plugins.json": {
      "key": ".obsidian/community-plugins.json",
      "existLocal": true,
      "mtimeLocal": 1650839896549,
      "mtimeLocalFmt": "2022-04-25T10:38:16+12:00",
      "sizeLocal": 21,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/core-plugins.json": {
      "key": ".obsidian/core-plugins.json",
      "existLocal": true,
      "mtimeLocal": 1650839864973,
      "mtimeLocalFmt": "2022-04-25T10:37:44+12:00",
      "sizeLocal": 241,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/hotkeys.json": {
      "key": ".obsidian/hotkeys.json",
      "existLocal": true,
      "mtimeLocal": 1650839864357,
      "mtimeLocalFmt": "2022-04-25T10:37:44+12:00",
      "sizeLocal": 2,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/workspace": {
      "key": ".obsidian/workspace",
      "existLocal": true,
      "mtimeLocal": 1650840028700,
      "mtimeLocalFmt": "2022-04-25T10:40:28+12:00",
      "sizeLocal": 2093,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/": {
      "key": ".obsidian/plugins/remotely-save/",
      "existLocal": true,
      "mtimeLocal": 1650839896481,
      "mtimeLocalFmt": "2022-04-25T10:38:16+12:00",
      "sizeLocal": 4096,
      "existRemote": false,
      "decision": "createFolder",
      "decisionBranch": 13
    },
    ".obsidian/plugins/remotely-save/.gitignore": {
      "key": ".obsidian/plugins/remotely-save/.gitignore",
      "existLocal": true,
      "mtimeLocal": 1650839895549,
      "mtimeLocalFmt": "2022-04-25T10:38:15+12:00",
      "sizeLocal": 10,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/data.json": {
      "key": ".obsidian/plugins/remotely-save/data.json",
      "existLocal": true,
      "mtimeLocal": 1650840089524,
      "mtimeLocalFmt": "2022-04-25T10:41:29+12:00",
      "sizeLocal": 1703,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/main.js": {
      "key": ".obsidian/plugins/remotely-save/main.js",
      "existLocal": true,
      "mtimeLocal": 1650839885809,
      "mtimeLocalFmt": "2022-04-25T10:38:05+12:00",
      "sizeLocal": 2051374,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/manifest.json": {
      "key": ".obsidian/plugins/remotely-save/manifest.json",
      "existLocal": true,
      "mtimeLocal": 1650839884761,
      "mtimeLocalFmt": "2022-04-25T10:38:04+12:00",
      "sizeLocal": 330,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    ".obsidian/plugins/remotely-save/styles.css": {
      "key": ".obsidian/plugins/remotely-save/styles.css",
      "existLocal": true,
      "mtimeLocal": 1650839886633,
      "mtimeLocalFmt": "2022-04-25T10:38:06+12:00",
      "sizeLocal": 691,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    "Untitled.md": {
      "key": "Untitled.md",
      "deltimeRemote": 1650840027704,
      "deltimeRemoteFmt": "2022-04-25T10:40:27+12:00",
      "existLocal": false,
      "existRemote": false,
      "decision": "keepRemoteDelHist",
      "decisionBranch": 7
    }
  }
}
```

```json
{
  "ts": 1650840029832,
  "tsFmt": "2022-04-25T10:40:29+12:00",
  "remoteType": "webdav",
  "mixedStates": {
    "test_note.md": {
      "key": "test_note.md",
      "existLocal": true,
      "mtimeLocal": 1650840027704,
      "mtimeLocalFmt": "2022-04-25T10:40:27+12:00",
      "sizeLocal": 0,
      "existRemote": false,
      "changeLocalMtimeUsingMapping": true,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    "Untitled.md": {
      "key": "Untitled.md",
      "deltimeLocal": 1650840027704,
      "deltimeLocalFmt": "2022-04-25T10:40:27+12:00",
      "existLocal": false,
      "existRemote": false,
      "decision": "uploadLocalDelHistToRemote",
      "decisionBranch": 6
    }
  }
}
```

**Comment by fyears** [comment]
```
    ".obsidian/": {
      "key": ".obsidian/",
      "existLocal": true,
      "mtimeLocal": 1650839896545,
      "mtimeLocalFmt": "2022-04-25T10:38:16+12:00",
      "sizeLocal": 4096,
      "existRemote": false,
      "decision": "createFolder",
      "decisionBranch": 13
    },
```

As you may see, remotely save doesn’t find out that the `.obsidian` folder exist, so every time of sync it tries to re-upload or re-create the folder. I suggest that may be you could try to find out the nginx config that “hide” the special `.obsidian` folder to the clients.

**Comment by tachyonicClock** [comment]
Looks like an outstanding issue with Nginx where PROPFIND does not work on hidden files.
https://github.com/arut/nginx-dav-ext-module/issues/41
https://github.com/arut/nginx-dav-ext-module/pull/62

**Comment by tachyonicClock** [comment]
Looks like this is caused by a bug in Nginx's web-dav implementation https://github.com/arut/nginx-dav-ext-module/issues/41

**Comment by fyears** [comment]
oh thanks for finding it out! hope you can find a fix then.

another way of working around the bug, is setting an encryption password in remotely save, so that the file names uploaded to the server is also encrypted, i.e., no longer contain dots in the file names.
