### ISSUE TITLE
[Bug]: The obsidian application closes due to RemoteIy Save on a smartphone (android)

### ISSUE THREAD

**Issue by Paulkpv** [remotely-save/remotely-save#841]
### What happened?

The obsidian application closes due to RemoteIy Save on a smartphone (android). If RemoteIy Save is disabled - all obsidian works fine. I use the Wedbay remote service, I use synchronization with Yandex disk

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Version of the plugin

0.5.24

### Version of Obsidian

1.6.7 (149)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
hi please try to skip large file firstly

**Comment by ShatterAshes** [comment]
I also experienced the same crash issue on my Android device

Error Log:
java.lang.OutOfMemoryError: Failed to allocate a 77793280 byte allocation with 52845544 free bytes and 50MB until OOM, target footprint 268435456, growth limit 268435456
	at android.util.Base64.decode(Base64.java:160)
	at android.util.Base64.decode(Base64.java:138)
	at android.util.Base64.decode(Base64.java:120)
	at com.capacitorjs.plugins.app.AppPlugin.requestUrlAndroid(AppPlugin.java:312)
	at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$3(AppPlugin.java:256)
	at com.capacitorjs.plugins.app.AppPlugin.$r8$lambda$j1HSgVflWKbjLrQ4iaQndJNl6yg(Unknown Source:0)
	at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda3.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by ThreeM-MMM** [comment]
Same Problem here. Android 15, Skip Large Files 20mb.

**Comment by fyears** [comment]
please try to set "skip large files"

**Comment by DaRacci** [comment]
surely this cant be accepted as just not going to work, there must be a way around this like flushing the buffer to file between data chunks.
