### ISSUE TITLE
[Bug]: 安卓端大文件同步闪退

### ISSUE THREAD

**Issue by lixingyu41** [remotely-save/remotely-save#884]
### What happened?

我在同步一个60Mb的pdf，每当同步到它软件就会闪退,我的存储空间够，内存16Gb，空闲内存有快8个G，工具抓取的日志如下
java.lang.OutOfMemoryError: Failed to allocate a 164728440 byte allocation with 50331648 free bytes and 81MB until OOM, target footprint 367434456, growth limit 402653184
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:98)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
	at android.util.Base64.encodeToString(Base64.java:459)
	at com.capacitorjs.plugins.app.AppPlugin.requestUrlAndroid(AppPlugin.java:350)
	at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$3(AppPlugin.java:256)
	at com.capacitorjs.plugins.app.AppPlugin.$r8$lambda$j1HSgVflWKbjLrQ4iaQndJNl6yg(Unknown Source:0)
	at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda3.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668)
	at java.lang.Thread.run(Thread.java:1012)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.5.25

### Version of Obsidian

1.7.4

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by lixingyu41** [comment]
还有几个其他的大文件，导致闪退的可能不是这个60M的

**Comment by fyears** [comment]
你的内存没有问题，但是obsidian api处理不了这个大文件。因此插件也无法处理。只能设置跳过大文件了
