### ISSUE TITLE
[Bug]: Startup failure

### ISSUE THREAD

**Issue by LiamSwayne** [remotely-save/remotely-save#888]
### What happened?

app.js:1 Plugin failure: remotely-save SyntaxError: Unexpected token '}' (at plugin:remotely-save:77:1)
    at eval (<anonymous>)
    at app.js:1:2199351
    at e.<anonymous> (app.js:1:2199452)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (Cloudflare R2)

### Version of the plugin

0.5.25

### Version of Obsidian

1.7.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by LiamSwayne** [comment]
I uninstalled and reinstalled the plugin and that fixed the bug, but it isn't a good fix to have to uninstall and reinstall whenever this happens.
